general:
  label: 基础设置
  items:
    cover:
      name: cover
      label: 首页背景图
      type: attachment
      default: '/casper/assets/images/blog-cover.jpg'
    links_cover:
      name: links_cover
      label: 友情链接页面背景图
      type: attachment
    archives_cover:
      name: archives_cover
      label: 归档页面背景图
      type: attachment
    post_copyright:
      name: post_copyright
      label: 文章版权信息
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    location:
      name: location
      label: 所在地
      type: text
    code_pretty:
      name: code_pretty
      label: 文章代码高亮主题
      type: select
      default: Default
      options:
        - value: Default
          label: Default
        - value: Coy
          label: Coy
        - value: Dark
          label: Dark
        - value: Okaidia
          label: Okaidia
        - value: Solarized Light
          label: Solarized Light
        - value: Tomorrow Night
          label: Tomorrow Night
        - value: Twilight
          label: Twilight
sns:
  label: 社交设置
  items:
    rss:
      name: rss
      label: RSS
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    twitter:
      name: twitter
      label: Twitter
      type: text
    facebook:
      name: facebook
      label: Facebook
      type: text
    instagram:
      name: instagram
      label: Instagram
      type: text
    dribbble:
      name: dribbble
      label: Dribbble
      type: text
    weibo:
      name: weibo
      label: 微博
      type: text
    email:
      name: email
      label: Email
      type: text
    qq:
      name: qq
      label: QQ
      type: text
    telegram:
      name: telegram
      label: Telegram
      type: text
    cnblog:
      name: cnblog
      label: 博客园
      type: text
    github:
      name: github
      label: Github
      type: text
    stackoverflow:
      name: stackoverflow
      label: Stack Overflow
      type: text